### ISSUE TITLE
Rex vs VS Code search?

### ISSUE THREAD

**Issue by milkbump** [antfu/rex#1]
VS Code seems to have all the features of Rex and more out of the box using the $# number syntax. Are there features of Rex I haven't discovered yet? I'm just curious.

In VS Code $0 gets the entire match, and $1 gets the first match, $2 second... etc.

![image](https://user-images.githubusercontent.com/20745107/124213591-89e30300-daf9-11eb-8222-7a16a1fa4510.png)

https://code.visualstudio.com/updates/v1_29#_multiline-search for even more.

**Comment by antfu** [comment]
Actually this is just a tool for my own need, I didn't expect ppl to use it (would be great if anyone find it useful, but not the goal). So, feel free to use whatever make sense to you :)

For the difference, as I said in the readme:

> Replacing via RegExp sounds like a good options to me, but somehow most editors can only do replacement but lack of the feature "keep only what matched".

VS Code provides the functionality of `string.replace` but sometimes I'd need `string.matchAll`, which for the most of the time, I would need to write a script every time to do the transform before I made this tool.
